### ISSUE TITLE
How to deal with this problem?

### ISSUE THREAD

**Issue by fanyuzeng** [zeus7777777/nav_a3c#1]
TypeError: unbound method preprocess_frame() must be called with Environment instance as first argument (got ndarray instance instead)

**Comment by zeus7777777** [comment]
Could you provide more detail about the problem? or how to reproduce this error.

**Comment by fanyuzeng** [comment]
Thank you, I solved this error. The problem is caused by python2,. I used your code in DeepMindLab(python2 version).
