### ISSUE TITLE
How to speed up the training process?

### ISSUE THREAD

**Issue by fanyuzeng** [zeus7777777/nav_a3c#5]
Except stairway_to_melon, training other mazes takes long times much more than 24 hours with the config.THREAD equal to 8.
I wonder whether there are some parameters of Deepmind lab I can adjust to speed up the training process. In addition, If I set config.THREAD=50, Can it speed up the process? or will it affect the episode-reward curve? 
Many thanks to you.

**Comment by zeus7777777** [comment]
One of the reasons may be this program use only CPU (because of the original paper's setting).
And how many threads to use depends on your CPU computation power.
In my case, training `nav_maze_static_01` took me more than 2 days on i7-3770 to converge.

**Comment by fanyuzeng** [comment]
You mean setting more thread can make convergence faster within CPU computation power? 
Are there parameters I can adjust in Deepmind lab to speed up the training process, like fast forward of TV?

**Comment by fanyuzeng** [comment]
I read A3C paper "Asynchronous methods for deep reinforcement learning" again. In general, setting more threads can speed up the training.

**Comment by fanyuzeng** [comment]
Are there parameters I can adjust in Deepmind lab to speed up the training process, like fast forward of TV?

**Comment by zeus7777777** [comment]
I'm not familiar with setting DeelmindLab setting.
And 
> In general, setting more threads can speed up the training.

is true when your CPU can afford to those many threads.

**Comment by fanyuzeng** [comment]
Ok, thank you so much ; )

My cpu can afford more than 30 threads.
