### ISSUE TITLE
 Where did 'arg' come from?

### ISSUE THREAD

**Issue by LGZY432** [zeus7777777/nav_a3c#6]
while True:
        cmd, arg = conn.recv()
        if cmd=='reset':
            env.reset()
            prev_action_vector = np.array([0]*7, dtype=np.intc)
            conn.send(env.observations())
        elif cmd=='action':
            reward = 0.0
            print('----- arg ------', arg)
            if arg>=0 and arg<6:
                prev_action_vector = np.copy(action_vector[arg])
                reward = env.step(prev_action_vector, num_steps=4)      # 4, 40
            elif arg==6:
                prev_action_vector[0] = 20
                reward = env.step(prev_action_vector, num_steps=4)     # 4, 40
            elif arg==7:
                prev_action_vector[0] = -20
                reward = env.step(prev_action_vector, num_steps=4)     # 4, 40
            running = env.is_running()
            obs = env.observations() if running else 0
            conn.send([obs, reward, running])
        elif cmd=='observe':
            conn.send([env.observations()['RGBD_INTERLACED']])
        elif cmd=='running':
            running = env.is_running()
            conn.send([running])
        elif cmd=='not_running':
            not_running = env.is_running()
            conn.send([not_running])
            env.reset()          
        elif cmd=='stop':
            break
************************************************************************************************
I looked through all the code and didn't see where'arg'came from.
If you know, you can guide me. Thanks very much！

**Comment by zeus7777777** [comment]
According to https://github.com/zeus7777777/nav_a3c/blob/master/environment.py#L24
`cmd, arg` will be set once received from `self.conn.send()`
hope that answered your question.

**Comment by LGZY432** [comment]
Thank you very much for your reply !!!
